//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsuranceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCustomer
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime dayOfBirth { get; set; }
        public string emailAddress { get; set; }
        public int Year { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public bool luxury { get; set; }
        public bool Dui { get; set; }
        public int tickets { get; set; }
        public bool liable { get; set; }
        public string Plate { get; set; }
    }
}
